[build]
  ignore = "bash scripts/netlify-ignore.sh"
  functions = "netlify/functions"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/style.css"
  [headers.values]
    Cache-Control = "public, max-age=600, must-revalidate"
